### ISSUE TITLE
Doesn't appear to work with Django 1.7.8

### ISSUE THREAD

**Issue by ursomniac** [dokterbob/django-newsletter#141]
running into django.core.exceptions.AppRegistryNotReady: Models aren't loaded yet.

This is when trying to do a syncdb.

**Comment by ursomniac** [comment]
OK - the problem occurs at line 26 of models.py:
User = get_user_model()

You can't reference a model at import time (in Django 1.7).  
See: https://docs.djangoproject.com/en/dev/ref/applications/

I'm not quite sure how to hack the code to make this work (though I'm surprised this is the first time I've run into this particular error)...   Suggestions for a workaround would be appreciated, since writing a whole other newsletter app when django-newsletter appears (from the docs) to do almost everything the client wants would be unfortunate!  :-)

**Comment by dokterbob** [comment]
The tests are running fine on Django 1.7 so there is probably something else wrong. Please double check whether you followed the installation instructions. If that doesn't solve the problem, please paste some of the relevant settings here.

**Comment by dokterbob** [comment]
Also see https://github.com/dokterbob/django-newsletter/blob/master/tests/settings.py for a reference.

**Comment by dokterbob** [comment]
(See https://coveralls.io/builds/3036773/source?filename=newsletter%2Fmodels.py for proof of coverage)

**Comment by ursomniac** [comment]
I tried to follow the installation instructions insofar as I could.   The source of the error is in the code where I pointed it out, and it's a clear 1.7 issue.  I don't know why your tests aren't catching it.

**Comment by ursomniac** [comment]
Here's the error dump - as you can see it hasn't hit any of my code yet...

(linews)[ 10:43 LINews/lowell-institute:develop ✗ ➭  ] python manage.py shell         
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/bob_donahue/Dev/__virtualenvs/linews/lib/python2.7/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/Users/bob_donahue/Dev/__virtualenvs/linews/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute
    django.setup()
  File "/Users/bob_donahue/Dev/__virtualenvs/linews/lib/python2.7/site-packages/django/__init__.py", line 21, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/bob_donahue/Dev/__virtualenvs/linews/lib/python2.7/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/Users/bob_donahue/Dev/__virtualenvs/linews/lib/python2.7/site-packages/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Users/bob_donahue/Dev/__virtualenvs/linews/lib/python2.7/site-packages/newsletter/models.py", line 26, in <module>
    User = get_user_model()
  File "/Users/bob_donahue/Dev/__virtualenvs/linews/lib/python2.7/site-packages/newsletter/utils.py", line 29, in get_user_model
    User = get_user_model()
  File "/Users/bob_donahue/Dev/__virtualenvs/linews/lib/python2.7/site-packages/django/contrib/auth/__init__.py", line 137, in get_user_model
    return django_apps.get_model(settings.AUTH_USER_MODEL)
  File "/Users/bob_donahue/Dev/__virtualenvs/linews/lib/python2.7/site-packages/django/apps/registry.py", line 199, in get_model
    self.check_models_ready()
  File "/Users/bob_donahue/Dev/__virtualenvs/linews/lib/python2.7/site-packages/django/apps/registry.py", line 131, in check_models_ready
    raise AppRegistryNotReady("Models aren't loaded yet.")
django.core.exceptions.AppRegistryNotReady: Models aren't loaded yet.

**Comment by ursomniac** [comment]
I've reviewed everything.   Fails on step 7 of the installation with the above error - basically any step involving manage.py has the same result (so one cannot even run the tests).  Given that steps 1-6 are straightforward (little room for 'user error'), it doesn't appear that I've missed anything.   Happy to provide specifics...

**Comment by respondcreate** [comment]
Hey @dokterbob !

Same issue here, your 0.5.2 release (the latest available to installed on PyPI) is incompatible with Django 1.7.x (the offending line in the v0.5.2 release is here: https://github.com/dokterbob/django-newsletter/blob/v0.5.2/newsletter/models.py#L26).

It looks like this code was removed in favor of this (https://github.com/dokterbob/django-newsletter/blob/master/newsletter/models.py#L36) so maybe it's just that you haven't pushed a newer release to PyPI in a while?

**Comment by ursomniac** [comment]
Yup - if I pull the master branch (instead of using pip install) and use that, things are groovy.   Thanks!

**Comment by dokterbob** [comment]
Hey all,

Please be aware that the latest 0.5.2 releas only supports the 1.5 and 1.4 release branches (see the (readme)[https://pypi.python.org/pypi/django-newsletter/0.5.2])) 1.7 and 1.8 support has been only recently added to the master branch. After enough user confirmation I will ship a new 0.6 release. 

Until that time please use the master branch - and feel free to fire issues.

Regards,
M
