### ISSUE TITLE
Invalid adress in send email 

### ISSUE THREAD

**Issue by christianwgd** [dokterbob/django-newsletter#326]
Hi, since the latest update i get an error message, when trying to subscribe:
Invalid address; only info@domain.de  could be parsed from "info@domain.de <info@domain.de>"
info@domain.de is the email address, which was set for "email" and "sender" in the newsletter.
Subscribe as an admin user doesn't have the problem.

Python 3.8.2, Django 3.0.7, django-newsletter 0.9.1

```python
Traceback (most recent call last):
  File "/var/venvs/teacup/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/var/venvs/teacup/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/var/venvs/teacup/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/var/venvs/teacup/lib/python3.8/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/var/venvs/teacup/lib/python3.8/site-packages/newsletter/views.py", line 459, in dispatch
    return super(SubscribeRequestView, self).dispatch(
  File "/var/venvs/teacup/lib/python3.8/site-packages/newsletter/views.py", line 155, in dispatch
    return super(ProcessUrlDataMixin, self).dispatch(*args, **kwargs)
  File "/var/venvs/teacup/lib/python3.8/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/var/venvs/teacup/lib/python3.8/site-packages/django/views/generic/edit.py", line 142, in post
    return self.form_valid(form)
  File "/var/venvs/teacup/lib/python3.8/site-packages/newsletter/views.py", line 421, in form_valid
    self.subscription.send_activation_email(action=self.action)
  File "/var/venvs/teacup/lib/python3.8/site-packages/newsletter/models.py", line 361, in send_activation_email
    message.send()
  File "/var/venvs/teacup/lib/python3.8/site-packages/django/core/mail/message.py", line 276, in send
    return self.get_connection(fail_silently).send_messages([self])
  File "/var/venvs/teacup/lib/python3.8/site-packages/django/core/mail/backends/smtp.py", line 109, in send_messages
    sent = self._send(message)
  File "/var/venvs/teacup/lib/python3.8/site-packages/django/core/mail/backends/smtp.py", line 121, in _send
    from_email = sanitize_address(email_message.from_email, encoding)
  File "/var/venvs/teacup/lib/python3.8/site-packages/django/core/mail/message.py", line 88, in sanitize_address
    raise ValueError(

Exception Type: ValueError at /newsletter/name/subscribe/
Exception Value: Invalid address; only info@domain.de  could be parsed from "info@domain.de <info@domain.de>"
```

**Comment by christianwgd** [comment]
Sorry for bothering, there are some inconsistencies in mail infrastructure. Better check that first and come back, when that was not the cause

**Comment by christianwgd** [comment]
Yes, was my newsletter configuration. For anyone who get the same error: I had configured the newsletter senders name with the same email as the email field. Seems that this is not allowed. As  soon i gave the sender a name without an "@" its working again. Although i have no idea why...

**Comment by middj2008** [comment]
I'm getting this same issue
ValueError at /send/notification/to/subscriber
Invalid address; only middj2008@gmail.com could be parsed from "middj2008@gmail.com, oluwaseunolumakin@gmail.com,

though I'm actually using an ajax to display the email addresses on the textarea specifying the name of the filed on the send_mail(subject, sender, recipient_list=[email]) as such but i getting this error again please any suggestion, though i followed you 

> Yes, was my newsletter configuration. For anyone who gets the same error: I had configured the newsletter senders name with the same email as the email field. Seems that this is not allowed. As soon i gave the sender a name without an "@" its working again. Although i have no idea why...

but still no idea why it giving that error
