### ISSUE TITLE
AssertionError: 404 != 200 Erorr in Django 1.5c1 version

### ISSUE THREAD

**Issue by imrancluster** [dokterbob/django-newsletter#60]
Dear,
I am new in python and django world. I need your help. 

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django_extensions/tests/uuid_field.py", line 48, in testUUIDField_pkAgregateCreate
    j = TestAgregateModel.objects.create(a=6)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/manager.py", line 149, in create
    return self.get_query_set().create(*_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 402, in create
    obj.save(force_insert=True, using=self.db)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 537, in save
    force_update=force_update, update_fields=update_fields)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 641, in save_base
    result = manager._insert([self], fields=fields, return_id=update_pk, using=using, raw=raw)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/manager.py", line 215, in _insert
    return insert_query(self.model, objs, fields, *_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 1661, in insert_query
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/compiler.py", line 937, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/mysql/base.py", line 122, in execute
    six.reraise(utils.IntegrityError, utils.IntegrityError(*tuple(e.args)), sys.exc_info()[2])
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/mysql/base.py", line 120, in execute
    return self.cursor.execute(query, args)
  File "/usr/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 174, in execute
    self.errorhandler(self, exc, value)
  File "/usr/lib/python2.7/dist-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
IntegrityError: (1452, 'Cannot add or update a child row: a foreign key constraint fails (`test_django_pydream`.`tests_testagregatemodel`, CONSTRAINT `testmodel_pk_ptr_id_refs_uuid_field_4c518bbb` FOREIGN KEY (`testmodel_pk_ptr_id`) REFERENCES `tests_testmodel_pk` (`uuid_field`))')
# 

FAIL: test_archive_detail (newsletter.tests.test_web.ArchiveTestcase)
## Test Submission detail view.

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/newsletter/tests/test_web.py", line 1034, in test_archive_detail
    self.assertEqual(response.status_code, 200)
AssertionError: 404 != 200

---

Ran 555 tests in 45.847s

FAILED (failures=1, errors=1, skipped=1, expected failures=1)
Destroying test database for alias 'default'...

Could you tell me please, How can I solve this problem?
## 

Thank You
Imran

**Comment by NeerajSinghNk** [comment]
Dear,
 I am a new in python flask framework help me to solve this problem.

Requirement already satisfied: requests in ./venv/lib/python3.6/site-packages
Requirement already satisfied: idna<3,>=2.5 in ./venv/lib/python3.6/site-packages (from requests)
Requirement already satisfied: chardet<4,>=3.0.2 in ./venv/lib/python3.6/site-packages (from requests)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in ./venv/lib/python3.6/site-packages (from requests)
Requirement already satisfied: certifi>=2017.4.17 in ./venv/lib/python3.6/site-packages (from requests)
F[2020-04-22 21:40:47,563] ERROR in app: Exception on /register [POST]
Traceback (most recent call last):
  File "/home/neeraj/myApp/venv/lib/python3.6/site-packages/flask/app.py", line 2353, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/neeraj/myApp/venv/lib/python3.6/site-packages/flask/app.py", line 1868, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/neeraj/myApp/venv/lib/python3.6/site-packages/flask/app.py", line 1866, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/neeraj/myApp/venv/lib/python3.6/site-packages/flask/app.py", line 1852, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/neeraj/myApp/app.py", line 41, in register
    flash("You are registered successfully and you can login","success")
  File "/home/neeraj/myApp/venv/lib/python3.6/site-packages/flask/helpers.py", line 408, in flash
    session["_flashes"] = flashes
  File "/home/neeraj/myApp/venv/lib/python3.6/site-packages/werkzeug/local.py", line 350, in __setitem__
    self._get_current_object()[key] = value
  File "/home/neeraj/myApp/venv/lib/python3.6/site-packages/flask/sessions.py", line 93, in _fail
    "The session is unavailable because no secret "
RuntimeError: The session is unavailable because no secret key was set.  Set the secret_key on the application to something unique and secret.
F
======================================================================
FAIL: test_login (test_app.user_endpoints_test)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/neeraj/myApp/test_app.py", line 41, in test_login
    self.assertEqual(self.app.get('/profile').status_code, 200)
AssertionError: 404 != 200

======================================================================
FAIL: test_register (test_app.user_endpoints_test)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/neeraj/myApp/test_app.py", line 34, in test_register
    self.assertTrue(self.value == 302 or self.value == 200)
AssertionError: False is not true

----------------------------------------------------------------------
Ran 2 tests in 0.740s
